machines = {
  "server-1"   => {"memory" => "1024", "cpu" => "1", "ip" => "100", "image" => "ubuntu/bionic64"},
  "server-2"   => {"memory" => "1024", "cpu" => "1", "ip" => "110", "image" => "ubuntu/bionic64"},
  "server-3"   => {"memory" => "1024", "cpu" => "1", "ip" => "120", "image" => "centos/7"},
  "server-4" => {"memory" => "1024", "cpu" => "1", "ip" => "130", "image" => "ubuntu/bionic64"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.kyros-vm"
      machine.vm.network "private_network", ip: "10.20.20.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/Kyros"]
      end
      machine.vm.provision "shell", path: "provision.sh"
      machine.vm.provision "shell", inline: "hostnamectl set-hostname #{name}.emp.example"
    end
  end
end