
---
- name: Download Zabbix Repository Ubuntu
  get_url: 
    url: https://repo.zabbix.com/zabbix/5.5/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.5-1%2Bubuntu20.04_all.deb
    dest: /tmp/zabbix-release_5.5-1+ubuntu20.04_all.deb
  
- name: Install Zabbix Repository Ubuntu
  dpkg_selections:
    name: zabbix-release_5.5-1+ubuntu20.04_all.deb
    selection: install

- name: Update SO Ubuntu
  apt:
    state: latest
    update_cache: yes

- name: Install Zabbix Agent Ubuntu
  apt:
    name: zabbix-agent
    state: latest
  
- name: Copy template zabbix-agent.conf Ubuntu
  template:
    src: templates/zabbix_agent.conf.j2
    dest: /etc/zabbix/zabbix-agent2.conf
  notify: Start service Ubuntu